sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
script:
  - 'curl -H "Authorization: token $(echo $GH_TOKEN)" https://api.github.com'
  - npm run deploy
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
