language: node_js

node_js:
- '0.10'

cache:
  directories:
  - node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

branches:
  only:
    - gh-pages

env:
  global:
    # saucelabs
    - secure: DBDZaLrin8wgzadzTt4fsFeDe/rSyHPLjnoD2d6RYPaIFXIkX8SbU81vZ7PMnLPm8iePuYfEguWv4BCAHJ62uY4GEKnKaRX9n66q6Be8WFbPaDaJ4JmdA0RJIj7N0CtXpH3puWfB7zx5/XvR2c4Cp+W7RwApebzifXzrtNXTqDE=
    - secure: XUPNz3Kkw0F+23dpJHZsucWKKe+zNGeg4/gy3+yaj79HZmuxB4X2XuDm1aRfissO7MoJmlUh0YVY6heQj1JeyBoCy8QB2NjDXrrkiHpf2z12jKv8uxoNQm4tY2/XOguD3I2hFPM/XZW/1wTsozpkLQuThr1H5PWDkSzoEg3VDXI=
  matrix:
  - WURST_CLIENT=node
  - WURST_CLIENT=selenium:firefox
  - WURST_CLIENT="saucelabs:internet explorer:10:Windows 8"

deploy:
  provider: npm
  email: stephan@boennemann.me
  skip_cleanup: true
  api_key:
    secure: Lq1FZweaNr/Ah8M7h3oWQ59HTswzvcksTUfzWb/dpqNn5FECN9I+4gi79EQPD62ZbJDCuDHY0EEEDLdnaB1z8N7kOj1RtmvC1k0teTEXFsGBPS4evXakRj+AfoBAGsTaXHqBYBOvYBxJT2Md/UoOgPSQjtAdZSNsmoFb1xkngQ0=
  on:
    branch: gh-pages
    repo: boennemann/semantic-release

sudo: false
